/debian/yadifad.conf /etc/yadifa/
/debian/apparmor/usr.sbin.yadifad /etc/apparmor.d/
/var/zones/masters/0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa.zone /var/lib/yadifa/masters/
/var/zones/masters/0.0.127.in-addr.arpa.zone /var/lib/yadifa/masters/
/var/zones/masters/localhost.zone /var/lib/yadifa/masters/
/var/zones/masters/localhost6.zone /var/lib/yadifa/masters/
usr/bin/yadifa
usr/sbin/yadifad
